### ISSUE TITLE
as 运行失败

### ISSUE THREAD

**Issue by beiliubei** [data-baker/BiaobeiSdkAndroidDemo#7]
Could not GET 'https://dl.bintray.com/data-baker/maven/com/baker/sdk/http/bakerhttp/1.0.3/bakerhttp-1.0.3.pom'. Received status code 403 from server: Forbidden

**Comment by data-baker** [comment]
> Could not GET 'https://dl.bintray.com/data-baker/maven/com/baker/sdk/http/bakerhttp/1.0.3/bakerhttp-1.0.3.pom'. Received status code 403 from server: Forbidden

您好，已经修复了哈，需要重新拉取代码。原因是dl.bintray.com这个平台的maven仓库升级迁移平台了。
